config/routes.rb
Rails.application.routes.draw do
  resources :socios
  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  
  resources :user_sessions
  resources :rifas
  resources :item_rifas do
    post "pay"
  end
  resources :users do
    member do
      post "suspender"
    end
  end
  root 'dashboard#index'

end

app/models/item_rifa.rb
# == Schema Information
#
# Table name: item_rifas
#
#  id         :integer          not null, primary key
#  fecha      :datetime
#  cantidad   :float
#  rifa_id    :integer
#  socio_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class ItemRifa < ActiveRecord::Base
	belongs_to :rifa
	belongs_to :socio
end

app/models/rifa.rb
# == Schema Information
#
# Table name: rifas
#
#  id         :integer          not null, primary key
#  periodo    :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Rifa < ActiveRecord::Base
	has_many :item_rifas

	after_save :create_items

	def create_items
		socios = Socio.all
		itemrifas = []
		itemrifa = nil
		contador = 0
		socios.each do |socio|
			for i in(0..11)
				fecha = self.periodo.to_time.beginning_of_year + i.month
				itemrifa = ItemRifa.new(:rifa_id => self.id, :socio_id => socio.id, :fecha => fecha)
				itemrifa.save
			end
		end
		# item_rifas << itemrifa
		# self.item_rifas << itemrifas
		# self.save
	end
end

app/models/socio.rb
# == Schema Information
#
# Table name: socios
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  apellido   :string(255)
#  cedula     :string(255)
#  telefono   :string(255)
#  direccion  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Socio < ActiveRecord::Base
	has_many :item_rifas
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  username         :string(255)      not null
#  crypted_password :string(255)      not null
#  salt             :string(255)      not null
#  suspendido       :boolean          default(FALSE)
#  socio_id         :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		
	end
end

app/controllers/item_rifas_controller.rb
class ItemRifasController < ApplicationController
	
	before_action :find_item, only: [:pay]

	def new
		@item_rifa = ItemRifa.new
	end

	def create
		@item_rifa = ItemRifa.new(item_rifa_params)
		@item_rifa.save
		respond_to do |format|
			format.js
		end
	end

	def pay
		@item.cantidad = 1
		@item.save
		respond_to do |format|
			format.html
			format.js
		end
	end

	private

	def item_rifa_params
		params.require(:item_rifa).permit :socio_id,
		:rifa_id,
		:fecha,
		:cantidad
	end

	def find_item
		@item = ItemRifa.find(params[:item_rifa_id])
	end
end

app/controllers/rifas_controller.rb
class RifasController < ApplicationController
	
	def index
		@socios = Socio.all
		@rifa = Rifa.last
		unless @rifa.nil?
			@grouped = @rifa.item_rifas.group_by &:socio_id
		end
	end

	def new
		@rifa = Rifa.new
	end

	def create
		@rifa = Rifa.new(rifa_params)
		@rifa.save
		respond_to do |format|
			format.js
		end
	end

	private

	def rifa_params
		params.require(:rifa).permit :periodo
	end
end

app/controllers/socios_controller.rb
class SociosController < ApplicationController
	# before_filter :require_login
  before_action :find_socio, only: [:show, :edit, :update, :destroy]
	def new
		@socio = Socio.new
	end

	def index
    @socios = Socio.all
  end

	def create
    @socio = Socio.new(socio_params)
    if @socio.save
    	redirect_to root_path, :notice => "Almacenado"
    else
    	redirect_to root_path, :notice => "Error"
    end
	end
  
  def show
    respond_to do |format|
      format.html
      format.js{ render "show" }
    end
  end


  def edit
    respond_to do |format|
      format.html
      format.js{ render "new_or_edit" }
    end
  end

  def update
    respond_to do |format|
      @socio.update(socio_params)
      format.html
      format.js { render "success"}
    end
  end

	private
	def find_socio
		@socio = Socio.find(params[:id])
	end

	def socio_params
		params.require(:socio).permit(:nombre, :direccion, :cedula, :telefono)
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def create 
		if @user = login(params[:username], params[:password])
			if @user.suspendido
				logout
				redirect_to login_path
				flash[:error] = "Usuario suspendido"
			else
				redirect_to root_path
				flash[:notice] = "Bienvenido #{current_user.username}"
			end
		else
			flash[:error] = "Usuario o contraseña inválido"
			redirect_to login_path
		end
	end

	def destroy
		logout
		redirect_to login_path, notice: "Has Cerrado Sesión"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_login

	def index
		@users = User.all
	end

	def show
	end

	def new
		@user = User.new
		@user.build_socio
	end

	def edit
    respond_to do |format|
    	format.js{ render "init" }
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path, notice: 'Usuario Creado'
  	else
  		render 'new'
  	end
  end

  def update
  	cliente_attrs = params[:user].delete :cliente_attributes
  	@cliente = Cliente.update(cliente_attrs[:id],cliente_attrs)
  	respond_to do |format|
  		if @user.update(user_params)
  			@users = User.all
  			format.html { redirect_to @user, notice: 'Usuario actualizado' }
  			format.json { render action: 'show', status: :created, location: @user }
  			format.js { render "success"}
  		else
        # raise 'error'
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js { render "success"}
      end
    end
  end

  def suspender
  	if @user.suspendido
  		@user.suspendido = false
  	else
  		@user.suspendido = true
  	end
  	@user.save
  	redirect_to users_path, :notice => "Usuario modificado"    
  end

  private 
  def user_params
  	params.require(:user).permit :username,
  	:password,
  	:password_confirmation,
  	:suspendido,
  	:cliente_attributes => [
  		:id,
  		:nombre,
  		:numero_de_identificacion,
  		:direccion,
  		:telefono,
  		:email
  	]
  end

  def set_user
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def local_date(date, tipo)
		if date.nil? == true
			date = "sin fecha"
		else
			case tipo
			when tipo = "date"
				date = date.strftime("%Y-%m-%d")
			when tipo = "datetime"
				date = date.strftime("%Y-%m-%d | %H:%M:%S")
			when tipo = "time"
				date = date.strftime("%H:%M")
			end
		end
		date
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/item_rifas_helper.rb
module ItemRifasHelper
end

app/helpers/rifas_helper.rb
module RifasHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="row">
	<div class="col-lg-10 col-md-10 col-sm-10 col-md-offset-1">
		<div class="well infobox ">
			<h4>AQUI DEBE MOSTRARSE INFORMACION RECIENTE</h4>
		</div>
	</div>
</div>

app/views/item_rifas/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 class="modal-title" id="myModalLabel"> <i class="mdi-navigation-check text-success"></i>Rifa</h3>
</div>
<%= form_for(@item_rifa, :remote => true) do |f| %>
<div class="modal-body">
  <div class= "field">
    <%= f.label :cantidad, "Cantidad:" %><br>
    <%= f.text_field :cantidad, :class => "form-control"%>
  </div>
</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  <%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/item_rifas/create.js.erb
<%- if @item_rifa.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  <%- @item_rifa.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  alertify.success("Almacenado");
<%- end %>

app/views/item_rifas/new.js.erb
m = $('#content_modal');
m.html('<%= j(render 'form', item_rifa: @item_rifa) %>');

app/views/item_rifas/pay.js.erb
<%- if @item.errors.any? %>
  <%- @item.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
$('#<%=@item.id %>').text("1.0");
$('#<%=@item.id %>').addClass("text-success");
  // alertify.success("Pagado");
<%- end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="flash_menssage">
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  </div>
  <% end %>
<% end %>
 

app/views/layouts/_modal.html.erb
<% if current_user %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="content_modal">
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="javascript:void(0)">MEDINAS</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav navbar">
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Socios <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Nuevo', new_socio_path()%></li>
          <li><%= link_to 'Lista', socios_path()%></li>
          <li class="divider"></li>
          <li><%= link_to 'Rifas', rifas_path()%></li>          
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.username %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Perfil', edit_user_path(current_user), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'}%></li>
          <li class="divider"></li>
          <li><%=link_to("Salir", :controller => 'user_sessions', :action => 'destroy')%></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cooperativa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
	<% if current_user %>
	<%= render 'layouts/navbar' %>
	<% else %>
	<div class="hero-unit text-info">
		<h2 class="text-center">Cooperativa</h2>
		<br>
	</div>
	<%end%> 
</header>
<body>
	<div role="main">
		<div class="container">
			<%= render 'layouts/flash' %>
			<%= yield %>
			<%= render 'layouts/modal' %>
		</div>
	</div>
</body>

</html>

app/views/rifas/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 class="modal-title" id="myModalLabel">Rifa</h3>
</div>
<%= form_for(@rifa, :remote => true) do |f| %>
<div class="modal-body">
  <div class= "field">
    <%= f.label :periodo, "Selecione anio" %><br>
    <%= f.text_field :periodo, :class => "form-control"%>
  </div>
</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  <%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/rifas/create.js.erb
<%- if @rifa.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  <%- @rifa.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  alertify.success("Almacenado");
<%- end %>

app/views/rifas/index.html.erb
<h1>Rifas 2015</h1>
<%= link_to 'Nueva Hoja', new_rifa_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "btn btn-info"}  %>
<% unless @rifa.nil? %>
<table class="table table-striped table-hover ">
	<thead>
		<tr>
			<th>Socio</th>
			<th>Enero</th>
			<th>Febrero</th>
			<th>Marzo</th>
			<th>Abril</th>
			<th>Mayo</th>
			<th>Junio</th>
			<th>Julio</th>
			<th>Agosto</th>
			<th>Septiembre</th>
			<th>Octubre</th>
			<th>Noviembre</th>
			<th>Diciembre</th>
		</tr>
	</thead>
	<tbody>
		<% @grouped.each do |socio, items|  %>
		<tr>
			<th><%= Socio.find(socio).nombre%></th>
			<% items.each do |item| %>
			<% if item.cantidad == 1 %>
				<td class="text-success"><%= item.cantidad %></td>
			<% else %>
				<td id="<%= item.id %>"><%= link_to item.cantidad, item_rifa_pay_path(item), method: :post, :remote => true %></td>
			<% end %>
			<% end %>
			<% end %>
		</tr>
	</tbody>
</table>
<% end %>

app/views/rifas/new.js.erb
m = $('#content_modal');
m.html('<%= j(render 'rifas/form', rifa: @rifa) %>');

app/views/socios/_form.html.erb
<%= form_for(@socio) do |f| %>
<%= f.text_field :nombre, :class => "form-control", :placeholder => "Ingrese Nombre" %>
<%= f.text_field :cedula, :class => "form-control", :placeholder => "Ingrese numero de cedula"  %>
<%= f.text_field :direccion, :class => "form-control", :placeholder => "Ingrese direccion "  %>
<%= f.text_field :telefono, :class => "form-control", :placeholder => "Ingrese telefono"  %>
<%= f.submit :guardar , :class => "btn btn-success btn-sm"  %>		
<% end %>

app/views/socios/edit.html.erb
<%= render "socios/form"%>

app/views/socios/index.html.erb
<div class="well infobox">
	<h4 class="text-center">Lista de Socios</h4>
	<div class="list-group">
		<% @socios.each do |s| %>
		<div class="list-group-item">
			<div class="row-action-primary">
				<i class="mdi-social-person"></i>
			</div>
			<div class="row-content">
				<div class="least-content"><%= link_to "editar", edit_socio_path(s) %></div>
				<h4 class="list-group-item-heading"><%= s.nombre  %></h4>
				<p class="list-group-item-text"><%= s.direccion  %></p>
				<p class="list-group-item-text"><%= s.telefono  %></p>
			</div>
		</div>
		<div class="list-group-separator"></div>
		<% end %>
	</div>
</div>

app/views/socios/new.html.erb
<div class="well infobox col-md-6 col-md-offset-3">
	<h3>Registro de Nuevos Socios</h3>
	<%= render "socios/form"  %>
</div>

app/views/user_sessions/new.html.erb
<div class="login">
  <div class="login-screen">
    <div class="app-title">
      <h2>
        <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-cutlery fa-stack-1x fa-inverse"></i>
        </span>
      </h2>
    </div>
    <%= form_tag user_sessions_path do %>
    <div class="login-form">
      <div class="control-group">
        <%= text_field_tag :username, params[:username], :placeholder => "Nombre de Usuario", :required => true, class: "login-field", id: "login-name" %>
        <label class="login-field-icon fui-user" for="login-name"></label>
      </div>
      <div class="control-group">
        <%= password_field_tag :password, "", :placeholder => "Contraseña", class: "login-field",id: "login-pass" %>
        <label class="login-field-icon fui-lock" for="login-pass"></label>
      </div>
      <%= submit_tag "Iniciar sesión", data: {disable_with: "Ingresando"}, class: "btn btn-primary btn-large btn-block" %>
      <a class="login-link" href="#">Olvidastes tu contraseña?</a>
    </div>
  </div>
  <% end %>
</div>